# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20171217_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='commands',
            field=models.TextField(),
        ),
    ]
