# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20171217_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='commands',
            field=models.CharField(max_length=2000),
        ),
    ]
